### ISSUE TITLE
Origin Count dependent on time when selection starts

### ISSUE THREAD

**Issue by ksiewert** [delt0r/msms#38]
I'm using the -SI with the -oOC option to stimulate selection on standing variation. It seems like the lower I set t as part of the -SI option, the higher the origin count becomes, given that the rest of the options stay constant. I'm having trouble reasoning through why this dependency would occur, as I would think they were independent. Does anyone have any intuition behind this behavior? Thank you!

**Comment by delt0r** [comment]
This is expected behavior. You are starting with standing variation, that is some fixed proportion of the population carries the mutation. At that time all lineages get a different mutation origin of the selected allele since they potently all have different backgrounds. If this is recent you have many lineages, if its a long way in the past you have only a few. 

The problem is that -oOC gives an origin count. Not a true "recurrent mutation" count. This is the only way it can be implemented with the -SI option.
